### ISSUE TITLE
Improve error message when failing to load dependencies 

### ISSUE THREAD

**Issue by Tpt** [helsing-ai/buffrs#178]
When loading
```toml
[package]
type = "api"
version = "0.0.0"

[dependencies]
package = { registry = "registry", version = "^0.1.1", repository = "repo" }
```

The `publish` commands fails with:
```
Error: 
   0: Failed to create release
   1: Failed to resolve dependency locally
   2: Failed to locate local manifest for package: hs-spine-event-publisher-api
   3: No such file or directory (os error 2)
```

It would be better to highlights the two possible reasons this fails:
* The version range is not supported yet
* The package is an `api` depending on an other `api`
